// <auto-generated />
using APIPROYECTO1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIPROYECTO1.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231026213718_BaseDatos")]
    partial class BaseDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIPROYECTO1.Models.Accesorios", b =>
                {
                    b.Property<int>("IdAccesorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccesorio"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.HasKey("IdAccesorio");

                    b.ToTable("Accesorios");

                    b.HasData(
                        new
                        {
                            IdAccesorio = 100,
                            Cantidad = 2,
                            Descripcion = "Collar blanco de plata",
                            Marca = "cartier",
                            Nombre = "Collar",
                            Precio = 11f
                        },
                        new
                        {
                            IdAccesorio = 101,
                            Cantidad = 3,
                            Descripcion = "Aretes largos",
                            Marca = "buccellati",
                            Nombre = "Aretes",
                            Precio = 20f
                        },
                        new
                        {
                            IdAccesorio = 1,
                            Cantidad = 2,
                            Descripcion = "Collar blanco de plata",
                            Marca = "cartier",
                            Nombre = "Collar",
                            Precio = 11f
                        },
                        new
                        {
                            IdAccesorio = 2,
                            Cantidad = 3,
                            Descripcion = "Aretes largos",
                            Marca = "buccellati",
                            Nombre = "Aretes",
                            Precio = 20f
                        });
                });

            modelBuilder.Entity("APIPROYECTO1.Models.Prenda", b =>
                {
                    b.Property<int>("IdPrenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrenda"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.HasKey("IdPrenda");

                    b.ToTable("Prendas");

                    b.HasData(
                        new
                        {
                            IdPrenda = 1,
                            Cantidad = 2,
                            Descripcion = "Pantalon",
                            Marca = "zara",
                            Nombre = "prenda1",
                            Precio = 40f
                        },
                        new
                        {
                            IdPrenda = 2,
                            Cantidad = 3,
                            Descripcion = "falda",
                            Marca = "zara",
                            Nombre = "prenda2",
                            Precio = 20f
                        });
                });

            modelBuilder.Entity("APIPROYECTO1.Models.Promocion", b =>
                {
                    b.Property<int>("IdPromocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPromocion"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.HasKey("IdPromocion");

                    b.ToTable("promociones");

                    b.HasData(
                        new
                        {
                            IdPromocion = 1,
                            Cantidad = 2,
                            Descripcion = "Blusa azul",
                            Marca = "shein",
                            Nombre = "Promocion 1",
                            Precio = 13f
                        },
                        new
                        {
                            IdPromocion = 2,
                            Cantidad = 3,
                            Descripcion = "Aretes largos",
                            Marca = "shein",
                            Nombre = "Promocion 2",
                            Precio = 15f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
